#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# https://www.apache.org/licenses/LICENSE-2.0
"""Validate the animated-SVG recordings that replaced the quick-start screenshots.

`docs/quick-start.md` used to carry one install screenshot per *harness* and
each `docs/<family>/README.md` one per *family* — fourteen stills, with a
design on file to grow them to twenty-five. Every one of them showed the same
thing, a plugin list with a plugin in it: proof that an install succeeded, and
nothing about the framework doing anything.

They were replaced by recordings of real runs. One for the quick start
(`/magpie-setup`), and one per family showing that family's *first* run — the
moment 65 of the 74 skills open with a silent pre-flight, find no
`<project-config>`, and stop to propose `/magpie-setup` rather than acting on
wrong assumptions. That arc is the thing worth showing, and a still cannot.

Two lists therefore have to agree — the families the frontmatter declares and
the recordings on disk — and the files themselves need checking in a way the
stills did not. These are *text*: an SVG that fails to parse still "exists", a
recording regenerated by hand loses the licence header `svg-term-cli` does not
write, and a long take balloons to megabytes that ship in every source
release. None of that shows up in review, because the diff of a generated SVG
is unreadable by design.

Checks:

- every family in the live `family:` frontmatter has its first-run recording,
  and every recording on disk belongs to a family — a family added without one
  ships a README with a broken image;
- the setup family is deliberately exempt: its first run *is* the quick-start
  recording, so `docs/setup/README.md` embeds that rather than a copy;
- every recording parses as XML with an `<svg>` root, carries the Apache
  licence header, and is under the size cap;
- every recording is actually embedded by the page that exists to show it, and
  every page that should show one does;
- nothing still points at the retired screenshots. Fourteen PNG stills and
  their `families/` layout were deleted; a doc that references one renders a
  broken image, and the offline link check does not cover every path that
  could reintroduce one.

Placeholders are *allowed*, exactly as they were for the stills: they are the
documented interim state (`assets/quickstart/README.md`) that keeps the pages
rendering and the offline link check passing until real recordings replace
them. They are reported on every run so the remaining work stays visible, but
they do not fail — a hook that blocked commits until someone sat down with
asciinema for ten takes would simply be disabled.
"""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

QUICKSTART = Path("assets/quickstart")
FAMILY_DIR = QUICKSTART / "families"
EXAMPLE_DIR = Path("assets/examples")
PLUGINS = Path("plugins")
SETUP_RECORDING = QUICKSTART / "magpie-setup.svg"
QUICK_START_DOC = Path("docs/quick-start.md")
RECORD_SCRIPT = Path("tools/dev/record-svg.sh")
SKILLS = Path("skills")

# Generous next to a terminal GIF and still small enough to not be felt in a
# source release. `record-svg.sh` warns at 1024 KB so a take that is drifting
# long is caught while the cast is still on disk to retrim.
MAX_BYTES = 1536 * 1024

# Written into the placeholders, and into nothing svg-term-cli emits.
PLACEHOLDER_MARKER = "data-magpie-placeholder"
LICENCE_MARKER = "Licensed to the Apache Software Foundation"
SVG_ROOT = "{http://www.w3.org/2000/svg}svg"

# One family's docs directory is not named after the family.
DOCS_DIR_OVERRIDES = {"issue": "issue-management"}

# The setup family's first run is the quick-start recording; it gets no copy.
EXEMPT_FAMILIES = {"setup"}

EXAMPLE_REF = re.compile(r"assets/examples/([A-Za-z0-9._-]+\.svg)")

# The set this replaced, so a stray reference to any of it fails loudly.
RETIRED = re.compile(r"assets/quickstart/(?:families/|)[A-Za-z0-9._-]+\.png")


def families() -> list[str]:
    """The live family list, from the frontmatter the plugins are built from."""
    found = set()
    for skill in SKILLS.glob("*/SKILL.md"):
        for line in skill.read_text().splitlines():
            if line.startswith("family:"):
                found.add(line.split("family:", 1)[1].strip())
                break
    return sorted(found)


def docs_readme(family: str) -> Path:
    return Path("docs") / DOCS_DIR_OVERRIDES.get(family, family) / "README.md"


def family_skills(family: str) -> set[str]:
    """The skills a family plugin actually ships, from the generated symlinks."""
    skills_dir = PLUGINS / f"magpie-{family}" / "skills"
    if not skills_dir.is_dir():
        return set()
    return {p.name for p in skills_dir.iterdir()}


def split_example(stem: str, known: list[str]) -> tuple[str, str] | None:
    """Split `<family>-<skill>` — both halves may contain hyphens, so the
    family list is what disambiguates it."""
    for family in sorted(known, key=len, reverse=True):
        prefix = f"{family}-"
        if stem.startswith(prefix):
            return family, stem[len(prefix) :]
    return None


def check_examples(known: list[str]) -> tuple[list[Path], list[str]]:
    """Example-command recordings: every file maps to a real command, and
    every file is embedded by a doc that references it."""
    errors: list[str] = []
    placeholders: list[Path] = []

    if not EXAMPLE_DIR.is_dir():
        return placeholders, errors

    referenced: set[str] = set()
    for doc in [*sorted(Path("docs").rglob("*.md")), Path("README.md")]:
        if doc.is_file():
            referenced |= set(EXAMPLE_REF.findall(doc.read_text()))

    on_disk = {p.name for p in EXAMPLE_DIR.glob("*.svg")}

    for name in sorted(referenced - on_disk):
        errors.append(f"{EXAMPLE_DIR / name}: referenced by the docs but missing")

    for path in sorted(EXAMPLE_DIR.glob("*.svg")):
        if path.name not in referenced:
            errors.append(f"{path}: no doc embeds this recording — drop it, or reference it")

        split = split_example(path.stem, known)
        if split is None:
            errors.append(
                f"{path}: does not start with a live family name — an example is "
                f"named <family>-<skill>, after the command it records"
            )
        else:
            family, skill = split
            if skill not in family_skills(family):
                errors.append(
                    f"{path}: magpie-{family} ships no skill {skill!r}, so "
                    f"/magpie-{family}:{skill} is not a command this records"
                )

        is_placeholder, errs = check_recording(path)
        errors += errs
        if is_placeholder:
            placeholders.append(path)

    return placeholders, errors


def check_recording(path: Path) -> tuple[bool, list[str]]:
    """Return (is_placeholder, errors) for one recording."""
    errors: list[str] = []

    if not path.is_file():
        return False, [f"{path}: missing — record it with {RECORD_SCRIPT}"]

    raw = path.read_bytes()

    if (n := len(raw)) > MAX_BYTES:
        errors.append(
            f"{path}: {n // 1024} KB exceeds the {MAX_BYTES // 1024} KB cap — "
            f"re-record something shorter, or trim it: "
            f"{RECORD_SCRIPT} <target> --cast <cast> --from <ms> --to <ms>"
        )

    text = raw.decode("utf-8", errors="replace")

    try:
        root = ET.fromstring(text)
    except ET.ParseError as exc:
        errors.append(f"{path}: not parseable as XML ({exc}) — it will render as nothing")
        return PLACEHOLDER_MARKER in text, errors

    if root.tag != SVG_ROOT:
        errors.append(
            f"{path}: root element is {root.tag!r}, expected an SVG root — the page embeds this as an image"
        )

    if LICENCE_MARKER not in text:
        errors.append(
            f"{path}: no Apache licence header. svg-term-cli does not write one; "
            f"regenerate with {RECORD_SCRIPT}, which prepends it"
        )

    return PLACEHOLDER_MARKER in text, errors


def check_embedded(doc: Path, recording: Path) -> list[str]:
    """A recording and the page that exists to show it must not drift apart."""
    if not doc.is_file():
        return [f"{doc}: missing"]
    if recording.name in doc.read_text():
        return []
    return [f"{doc}: does not embed {recording} — the page this recording exists for"]


def check_no_retired_references() -> list[str]:
    """Fourteen stills were deleted. Nothing may point at them again."""
    errors: list[str] = []

    for png in sorted(QUICKSTART.rglob("*.png")):
        errors.append(
            f"{png}: the quick-start screenshot set was retired in favour of the "
            f"recordings — a new still here is shown by nothing"
        )

    for doc in [*sorted(Path("docs").rglob("*.md")), Path("README.md")]:
        if not doc.is_file():
            continue
        # The design doc records the retired set as history, in prose that
        # explains the replacement. Only live references matter here.
        if doc.parts[:2] == ("docs", "designs"):
            continue
        for match in sorted(set(RETIRED.findall(doc.read_text()))):
            errors.append(f"{doc}: references retired screenshot {match}")

    return errors


def main() -> int:
    errors: list[str] = []
    placeholders: list[Path] = []

    expected = {SETUP_RECORDING: QUICK_START_DOC}
    for family in families():
        if family in EXEMPT_FAMILIES:
            # Its first run is the quick-start recording — check it embeds that.
            errors += check_embedded(docs_readme(family), SETUP_RECORDING)
            continue
        expected[FAMILY_DIR / f"{family}-first-run.svg"] = docs_readme(family)

    for recording, doc in sorted(expected.items()):
        is_placeholder, errs = check_recording(recording)
        errors += errs
        errors += check_embedded(doc, recording)
        if is_placeholder:
            placeholders.append(recording)

    # No orphans: a recording no family claims is one no page can be showing.
    if FAMILY_DIR.is_dir():
        for stray in sorted(FAMILY_DIR.glob("*.svg")):
            if stray not in expected:
                errors.append(
                    f"{stray}: no family claims this recording — drop it, or add "
                    f"the family to the frontmatter"
                )

    example_placeholders, example_errors = check_examples(families())
    errors += example_errors
    placeholders += example_placeholders

    errors += check_no_retired_references()

    if errors:
        for err in errors:
            print(f"error: {err}", file=sys.stderr)
        return 1

    if placeholders:
        print(
            f"note: {len(placeholders)} recordings are still placeholders: "
            f"{', '.join(p.name for p in placeholders)}"
        )
        print(f"      record them with {RECORD_SCRIPT} <target>")

    total = len(expected) + len(list(EXAMPLE_DIR.glob("*.svg")))
    print(f"Quick-start and example recordings OK ({total} files).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
